version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inter
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
